### ISSUE TITLE
New wheels for Python 3.11

### ISSUE THREAD

**Issue by aPeter1** [bonfus/musr2py#1]
Hello! 

When I try to install this package using pip I get this:

`ERROR: Could not build wheels for musr2py, which is required to install pyproject.toml-based projects`

It seems like there may be a new distributable you need to build for python 3.11, but I'm not very familiar on that whole process. Let me know if I can help. Thanks!

**Comment by aPeter1** [comment]
If you'd like to give me permissions to help you with updating those in the future, I'd be happy to do so as well! I've contributed to a few MuSR projects on Github.

**Comment by bonfus** [comment]
Thanks for sharing the bug! Can you help me reproduce the problem?

I tried:

```
pip install git+https://github.com/bonfus/musr2py.git
Collecting git+https://github.com/bonfus/musr2py.git
  Cloning https://github.com/bonfus/musr2py.git to ./pip-req-build-_cadmcq9
  Running command git clone --filter=blob:none --quiet https://github.com/bonfus/musr2py.git /tmp/pip-req-build-_cadmcq9
  Resolved https://github.com/bonfus/musr2py.git to commit a96481212bc8b66c86d69c3eda1120bde7412956
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: musr2py
  Building wheel for musr2py (pyproject.toml) ... done
  Created wheel for musr2py: filename=musr2py-0.0.1-cp310-cp310-linux_x86_64.whl size=140451 sha256=ca8ee84a4274aa7aed6fc24d1c42a7395ba516cadc29eb07e0a624d60eadb11d
  Stored in directory: /tmp/pip-ephem-wheel-cache-r9glzvwe/wheels/46/7e/af/8d43e8e7453349dde7e58fa34b64abb5b24a5162119d84e41e
Successfully built musr2py
Installing collected packages: musr2py
Successfully installed musr2py-0.0.1
```

and everything went fine.

Edit: sorry my bad, I didn't notice I was still using python 3.10!

**Comment by bonfus** [comment]
Wheels for python 3.11 are now available here:

https://github.com/bonfus/musr2py/actions/runs/3670024399

(bottom in artifact.zip).

Soon also on pypi.

**Comment by bonfus** [comment]
Now also on pypi. Closing.

**Comment by aPeter1** [comment]
Thank you! We really appreciate this package. Out of curiosity, are you able to adjust your wheels.yml file to run for macos-latest as well? I'm running our testing suit on macos-latest and windows/ubuntu run fine, and macos-latest doesn't raise exceptions, it just can't get data out of the files (and I'm asserting the file paths are correct)
